---
- name: Install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags:
    - docker
  become: yes
# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- name: Add Dockers official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker
  become: yes

# sudo apt-key fingerprint 0EBFCD88
- name: Verify that we have the key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker
  become: yes

# sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
- name: Set up the stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
  tags:
    - docker
  become: yes

# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - docker
  become: yes

# sudo apt-get install docker-ce=18.03.*
- name: Install docker
  apt:
    name: docker-ce=18.03.*
    state: present
    update_cache: yes
  tags:
    - docker
  become: yes
# sudo groupadd docker
- name: Create "docker" group
  group:
    name: docker
    state: present
  tags:
    - docker
  become: yes
# sudo usermod -aG docker ubuntu
- name: Add remote "ubuntu" user to "docker" group
  user:
    name: ubuntu
    group: docker
    append: yes
  tags:
    - docker
  become: yes
# sudo curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
# sudo chmod +x /usr/local/bin/docker-compose
- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.20.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
  tags:
    - docker
  become: yes

- name: install python pip
  raw: apt install -y python-pip
  become: yes

- name: install python-Dockers
  raw: apt install -y python-docker
  become: yes

- name: Install Nginx
  docker_container:
    name: nginx
    image: nginx
    detach: True
    ports:
        - 80:80
    expose:
        - 80
  become: yes
